# Generated by Django 4.2 on 2023-05-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menusection",
            name="section_name",
            field=models.CharField(
                choices=[
                    ("PizzaRegular", "Pizza Regular"),
                    ("PizzaSicilian", "Pizza Sicilian"),
                    ("Topping", "Topping"),
                    ("Sub", "Sub"),
                ],
                max_length=30,
            ),
        ),
    ]
