# Generated by Django 4.2 on 2023-05-10 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="items",
            old_name="section",
            new_name="name",
        ),
    ]
