# Generated by Django 4.2 on 2023-05-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_menusection_section_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menusection",
            name="section_name",
            field=models.CharField(max_length=30),
        ),
    ]
