# Generated by Django 4.2 on 2023-06-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0002_alter_platesincart_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="platesincart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
