# Generated by Django 4.2 on 2023-06-18 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0003_platesincart_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platesincart",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
